# =============================================================================
# SITE CONFIGURATION - BUILD ENGINE
# THIS FILE IS USED EXCLUSIVELY BY THE THEME REPOSITORY BUILD PIPELINE.
# FOR YOUR PERSONAL WEBSITE, USE 'config.toml.example' AS A TEMPLATE,
# FILL IT WITH YOUR DATA, AND RENAME IT TO 'config.toml'.
# =============================================================================

base_url = "https://nobraininside.github.io/zola-386-nojs/"
title = "Zola-386-nojs Theme Demo"
theme = "zola-386-nojs"

taxonomies = [
  {name = "categories", paginate_by = 5, rss = true},
  {name = "tags", paginate_by = 5, rss = true},
]

[extra]
brand = 'C:\>_SYSTEM_LOG'
year = "2026"
author = "Your Name"
author_url = "https://your-website.com"
social = "Mastodon"
social_url = "https://your-social-url"
vat = "00000000000"

zola386_menu = [
    {path="", name="Home"},
    {path="categories", name="Categories"},
    {path="tags", name="Tags"},
    {path="about", name="About"},
]
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_author = "Author"
label_date = "Date"
label_taxonomy = "Taxonomy"
label_reading = "Reading time"
label_read_more = "Read more"

