# =============================================================================
# SITE CONFIGURATION - BUILD ENGINE
# THIS FILE IS USED EXCLUSIVELY BY THE THEME REPOSITORY BUILD PIPELINE.
# FOR YOUR PERSONAL WEBSITE, USE 'config.toml.example' AS A TEMPLATE,
# FILL IT WITH YOUR DATA, AND RENAME IT TO 'config.toml'.
# =============================================================================

base_url = "https://nobraininside.github.io/zola-386-nojs/"
title = "Zola-386-nojs Theme Demo"
theme = "zola-386-nojs"

[extra]
brand = 'C:\>_SYSTEM_LOG'
# Queste sono le variabili che causano l'errore
zola386_menu = [
    {path="", name="Home"},
    {path="categories", name="Categories"},
    {path="tags", name="Tags"},
    {path="about", name="About"},
]
label_tags = "Tags"
label_date = "Date"
label_reading = "Reading time"

taxonomies = [
  {name="categories", rss=true},
  {name="tags", rss=true},
]