name: Deploy Zola

on:
  push:
      branches:
            - main

jobs:
  build:
      runs-on: ubuntu-latest
          steps:
	        - uses: actions/checkout@v4
		- name: Build with Zola
		uses: shalzz/zola-deploy-action@v0.19.2
		env:
		  BUILD_ONLY: true
		  TOKEN: ${{ secrets.GITHUB_TOKEN }}
		  PAGES_BRANCH: gh-pages